### PR TITLE
Add code comments to explain `touch-action` setting

### PR DESCRIPTION
**Pull request by lolmaus**

### CODE REVIEW

**Comment by nickschot** [comment]
After thinking about this again (its been a while..) I think the behaviour was correct. Example: we want to handle a horizontal panning action ourselves (axis: horizontal) meaning we want the browser to disable the default handling of that. We do still want to keep vertical touch gestures enabled for default behaviour (for example scrolling). As such we need to add `touch-action: pan-y` to disable default horizontal panning features in the browser. 

The same behaviour can also be observed in, for example, HammerJS.

**Comment by knownasilya** [comment]
Probably need to leave a comment in the code explaining what's happening :D

**Comment by lolmaus** [comment]
@nickschot Thx for the explanation! I've reverted my change.

@knownasilya Explanation added.

Please re-review.

**Review by nickschot — APPROVED** [review]

**Comment by nickschot** [comment]
Thanks for the PR!

**Pull request merged**
